app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/admin',function(){
    return view('admin.index');
});

Route::group(['middleware'=>'admin'],function(){

    Route::resource('admin/users','AdminUsersController');
    Route::resource('admin/posts','AdminPostsController');
    Route::resource('admin/categories','AdminCatrgoriesController');
    Route::resource('admin/media','AdminMediaController');
    //Route::get('admin/media/upload',['as'=>'admin.media.upload','uses'=>'AdminMediaController@store']);
});

app/User.php
<?php

namespace App;
use Illuminate\Support\Facades\Hash;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id','photo_id','is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function role()
    {
      return $this->belongsTo('App\Role');
    }
    public function photo()
    {
      return $this->belongsTo('App\Photo');
      // code...
    }
    public function setPasswordAttribute($password){
      if(!empty($password)){
        $this->attributes['password'] = \Hash::make($password);
      }
    }
    public function isAdmin()
    {
      if($this->role->name =="Administrator" && $this->is_active ==1){
        return true;
      }
      return false;
    }
    public function posts(){
      return $this->hasMany('App\Post');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
  <h1>Create Users</h1>

    {!! Form::open(['method'=>'POST', 'action'=>'AdminUsersController@store','files'=>true])  !!}
      <div class="form-group">
        {!! Form::label('name','Name:') !!}
        {!! Form::text('name', null, ['class'=>'form-control'] ) !!}
      </div>

      <div class="form-group">
        {!! Form::label('email','Email:') !!}
        {!! Form::email('email', null, ['class'=>'form-control'] ) !!}
      </div>

      <div class="form-group">
        {!! Form::label('role_id','Role:') !!}
        {!! Form::select('role_id',[''=>'Choose Options'] + $roles, null, ['class'=>'form-control'] ) !!}
      </div>

      <div class="form-group">
        {!! Form::label('is_active','Status:') !!}
        {!! Form::select('is_active',array(1=>'Active',0=>'Not Active'), 0, ['class'=>'form-control'] ) !!}
      </div>

      <div class="form-group">
        {!! Form::label('photo_id','Photo:') !!}
        {!! Form::file('photo_id', null, ['class'=>'form-control'] ) !!}
      </div>

      <div class="form-group">
        {!! Form::label('password','Password:') !!}
        {!! Form::password('password', ['class'=>'form-control'] ) !!}
      </div>

      <div class="form-group">
        {!! Form::submit('Create User', ['class'=>'btn btn-primary']) !!}
      </div>
    {!! Form::close() !!}

    @include('includes.form_error')


@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
  <h1>Edit Users</h1>
  <div class="row">


      <div class="col-sm-3">
        <img src="{{$user->photo ? $user->photo->file : 'http://placehold.it/400x400'}}" alt="" class="img-responsive img-rounded">
      </div>



          <div class="col-sm-9">


            {!! Form::model($user, ['method'=>'PATCH', 'action'=>['AdminUsersController@update',$user->id],'files'=>true])  !!}
              <div class="form-group">
                {!! Form::label('name','Name:') !!}
                {!! Form::text('name', null, ['class'=>'form-control'] ) !!}
              </div>

              <div class="form-group">
                {!! Form::label('email','Email:') !!}
                {!! Form::email('email', null, ['class'=>'form-control'] ) !!}
              </div>

              <div class="form-group">
                {!! Form::label('role_id','Role:') !!}
                {!! Form::select('role_id',$roles, null, ['class'=>'form-control'] ) !!}
              </div>

              <div class="form-group">
                {!! Form::label('is_active','Status:') !!}
                {!! Form::select('is_active',array(1=>'Active',0=>'Not Active'), null, ['class'=>'form-control'] ) !!}
              </div>

              <div class="form-group">
                {!! Form::label('photo_id','Photo:') !!}
                {!! Form::file('photo_id', null, ['class'=>'form-control'] ) !!}
              </div>

              <div class="form-group">
                {!! Form::label('password','Password:') !!}
                {!! Form::password('password', ['class'=>'form-control'] ) !!}
              </div>

              <div class="form-group">
                {!! Form::submit('Update User', ['class'=>'btn btn-primary col-sm-6']) !!}
              </div>
            {!! Form::close() !!}

            {!! Form::open (['method'=>'DELETE','action'=>['AdminUsersController@destroy',$user->id]]) !!}
              <div class="form-group">
                {!! Form::submit('Delete User',['class'=>'btn btn-danger col-sm-6']) !!}
              </div>

            {!!Form::close() !!}

          </div>
        </div>
      <div class="row">
      @include('includes.form_error')
      </div>



@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')

  @if(Session::has('deleted_user'))

  <div class="alert alert-warning">
  <strong>Warning!</strong> {{session('deleted_user')}}
  </div>
  @endif


  @if(Session::has('updated_user'))

  <div class="alert alert-info">
  <strong>Info!</strong> {{session('updated_user')}}
  </div>

  @endif


<h1>Users</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Photo</th>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Status</th>
        <th>Created</th>
        <th>Updated</th>
      </tr>
    </thead>
    <tbody>
      @if($users)
        @foreach($users as $user)
      <tr>
        <td>{{$user->id}}</td>
        <td><a href="{{route('admin.users.edit',$user->id)}}"><img class="img-rounded" height="50" width="60" src="{{$user->photo ? $user->photo->file : 'http://placehold.it/50x50'}}" alt="" ></a></td>
        <td><a href="{{route('admin.users.edit',$user->id)}}">{{$user->name}}</a></td>
        <td>{{$user->email}}</td>
        <td>{{$user->role->name}}</td>
        <td>{{$user->is_active==1 ? 'Active':'Not active' }}</td>
        <td>{{$user->created_at->diffForHumans()}}</td>
        <td>{{$user->updated_at->diffForHumans()}}</td>
      </tr>
        @endforeach
        @endif
    </tbody>
  </table>

@stop