app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/admin',function(){
    return view('admin.index');
});

Route::group(['middleware'=>'admin'],function(){

    Route::resource('admin/users','AdminUsersController');
    Route::resource('admin/posts','AdminPostsController');
    Route::resource('admin/categories','AdminCatrgoriesController');
    Route::resource('admin/media','AdminMediaController');
    //Route::get('admin/media/upload',['as'=>'admin.media.upload','uses'=>'AdminMediaController@store']);
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $fillable =[
      'category_id',
      'photo_id',
      'title',
      'body'

    ];

public function user(){
  return $this->belongsTo('App\User');
}

public function photo(){
  return $this->belongsTo('App\Photo');
}

public function category(){
  return $this->belongsTo('App\Category');
}


}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')

@section('content')

  <h1>Create Posts</h1>
<div class="row">

  {!! Form::open(['method'=>'POST', 'action'=>'AdminPostsController@store','files'=>true])  !!}
    <div class="form-group">
      {!! Form::label('title','Title:') !!}
      {!! Form::text('title', null, ['class'=>'form-control'] ) !!}
    </div>

    <div class="form-group">
      {!! Form::label('category_id','Category:') !!}
      {!! Form::select('category_id',[''=>'Choose Category']+ $categories, null, ['class'=>'form-control'] ) !!}
    </div>

    <div class="form-group">
      {!! Form::label('photo_id','Photo:') !!}
      {!! Form::file('photo_id', null, ['class'=>'form-control '] ) !!}
    </div>

    <div class="form-group">
      {!! Form::label('body','Description:') !!}
      {!! Form::textarea('body',null, ['class'=>'form-control'] ) !!}
    </div>

    <div class="form-group">
      {!! Form::submit('Create Post', ['class'=>'btn btn-primary']) !!}
    </div>
  {!! Form::close() !!}
</div>

<div class="row">
  @include('includes.form_error')

</div>

@stop

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')

@section('content')

  <h1>Edit Posts</h1>
<div class="row">
  <div class="col-sm-3">

    <img class="img-responsive" src="{{$post->photo->file}}" alt="">
  </div>




  <div class="col-sm-9">



  {!! Form::model($post, ['method'=>'PATCH', 'action'=>['AdminPostsController@update',$post->id],'files'=>true])  !!}
    <div class="form-group">
      {!! Form::label('title','Title:') !!}
      {!! Form::text('title', null, ['class'=>'form-control'] ) !!}
    </div>

    <div class="form-group">
      {!! Form::label('category_id','Category:') !!}
      {!! Form::select('category_id', $categories, null, ['class'=>'form-control'] ) !!}
    </div>

    <div class="form-group">
      {!! Form::label('photo_id','Photo:') !!}
      {!! Form::file('photo_id', null, ['class'=>'form-control '] ) !!}
    </div>

    <div class="form-group">
      {!! Form::label('body','Description:') !!}
      {!! Form::textarea('body',null, ['class'=>'form-control'] ) !!}
    </div>

    <div class="form-group">
      {!! Form::submit('Update Post', ['class'=>'btn btn-primary col-sm-6']) !!}
    </div>
  {!! Form::close() !!}

  {!! Form ::open(['method'=>'DELETE', 'action'=>['AdminPostsController@destroy',$post->id]]) !!}

    <div class="form-group">
      {!! Form::submit('Delete Post',['class'=>'btn btn-danger col-sm-6']) !!}
    </div>

  {!! Form::close() !!}
  </div>

</div>

<div class="row">
  @include('includes.form_error')

</div>

@stop

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')

@section('content')

@if(Session::has('deleted_post'))

<div class="alert alert-warning">
<strong>Warning!</strong> {{session('deleted_post')}}
</div>
@endif


  <h1>Posts</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Photo</th>
        <th>Owner</th>
        <th>Category</th>

        <th>Title</th>
        <th>Body</th>
        <th>Created</th>
        <th>Updated</th>
      </tr>
    </thead>
    <tbody>
      @if($posts)
        @foreach($posts as $post)
      <tr>
        <td>{{$post->id}}</td>
        <td> <a href="{{route('admin.posts.edit',$post->id)}}"> <img height="50" src="{{$post->photo ? $post->photo->file : 'http://placehold.it/50x50'}}" alt=""> </a></td>
        <td><a href="{{route('admin.posts.edit',$post->id)}}">{{$post->user->name}} </a></td>
        <td>{{$post->category ? $post->category->name : 'uncategorized'}}</td>

        <td>{{$post->title}}</td>
        <td>{{$post->body}}</td>
        <td>{{$post->created_at->diffForHumans()}}</td>
        <td>{{$post->updated_at->diffForHumans()}}</td>
      </tr>
        @endforeach
        @endif
    </tbody>
  </table>

@stop