app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/admin',function(){
    return view('admin.index');
});

Route::group(['middleware'=>'admin'],function(){

    Route::resource('admin/users','AdminUsersController');
    Route::resource('admin/posts','AdminPostsController');
    Route::resource('admin/categories','AdminCatrgoriesController');
    Route::resource('admin/media','AdminMediaController');
    //Route::get('admin/media/upload',['as'=>'admin.media.upload','uses'=>'AdminMediaController@store']);
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable=['name'];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')

<h1>Categories</h1>

<div class="col-sm-6">

    {!! Form::model($category,['method'=>'PATCH', 'action'=>['AdminCatrgoriesController@update',$category->id]])  !!}

    <div class="form-group">

      {!! Form::label('name','Name:') !!}
      {!! Form::text('name', null, ['class'=>'form-control'] ) !!}

    </div>

    <div class="form-group">
      {!! Form::submit('Update Category', ['class'=>'btn btn-primary col-sm-6']) !!}
    </div>

    {!! Form::close() !!}
    {!! Form::open(['method'=>'DELETE', 'action'=>['AdminCatrgoriesController@destroy', $category->id]])  !!}

    <div class="form-group">
      {!! Form::submit('Delete Category', ['class'=>'btn btn-danger col-sm-6']) !!}
    </div>

    {!! Form::close() !!}
</div>







@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')

<h1>Categories</h1>

<div class="col-sm-6">

    {!! Form::open(['method'=>'POST', 'action'=>'AdminCatrgoriesController@store'])  !!}

    <div class="form-group">

      {!! Form::label('name','Name:') !!}
      {!! Form::text('name', null, ['class'=>'form-control'] ) !!}

    </div>

    <div class="form-group">
      {!! Form::submit('Create Category', ['class'=>'btn btn-primary']) !!}
    </div>

    {!! Form::close() !!}
</div>




<div class="col-sm-6">

  @if($categories)

  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Created Date</th>
      </tr>
    </thead>
    @foreach($categories as $category)
    <tbody>
      <tr>

      <td><a href="{{route('admin.categories.edit',$category->id)}}">{{$category->id}} </a></td>
      <td><a href="{{route('admin.categories.edit',$category->id)}}"> {{$category->name}}</a></td>
      <td>{{$category->created_at ? $category->created_at->diffForHumans() : 'Not Dated'}}</td>
      </tr>
    </tbody>
    @endforeach


  </table>
  @endif

</div>

@stop